use reverse DNS name for app extension Id
MicrosoftDocs/windows-uwp pull request #1131
Opened 2018-10-26 15:49 UTC by ChrisGuzak

the build video says, and the [manifest schema](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-appextension-manual) demonstrates using reverse DNS names for the app extension Id. I've updated this page to match that guidance.

2018-10-26 21:44 UTC, dkbennett requested changes
There is a 3rd reference to this extension name further down the page under "Debugging app extensions and hosts".  That one should also be changed.

2018-10-26 23:08 UTC, ChrisGuzak commented
thanks for catching that. fixed.

2018-10-27 01:50 UTC, ChrisGuzak commented
ready for a reviewer to approve

2018-10-29 18:19 UTC, mikematteson commented
@jillre : PR **passed** acceptance checklist. Need content owner review and approval. Assigning to you, but please reassign if new owner has been identified. Thanks!

2018-10-29 21:06 UTC, ChrisGuzak commented
@dkbennett are you the content owner? do you know who is?

2018-11-01 20:45 UTC, merged