Add Remote Deployment to PC
MicrosoftDocs/windows-uwp pull request #116
Opened 2017-06-01 23:15 UTC by hpsin

cc @cdonthini and @PatrickFarley

2017-06-01 23:15 UTC, msftclas commented
@hpsin,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-02 05:50 UTC, c-don commented on windows-apps-src/debug-test-perf/deploying-and-debugging-uwp-apps.md
> +  `Xbox: \\MY-DEVKIT\DevelopmentFiles\XrfsFiles` - this is a symlink to the **package registration path**
do we want to say stuff about the symlink. Maybe there is a reason, Xbox avoided that. We can just say- On PC, we register to the package registration path. what do you think

2017-06-02 05:50 UTC, c-don requested changes
looks good! One small comment regarding the symlink.

2017-06-14 17:08 UTC, hpsin commented on windows-apps-src/debug-test-perf/deploying-and-debugging-uwp-apps.md
> +  `Xbox: \\MY-DEVKIT\DevelopmentFiles\XrfsFiles` - this is a symlink to the **package registration path**
Fine as is, it's a symlink, no need to hide that. Clarifies why it looks like files are being copied to disk.

2017-06-14 17:14 UTC, PatrickFarley approved these changes

2017-06-14 17:16 UTC, merged