Added package formats
MicrosoftDocs/windows-uwp pull request #2566
Opened 2020-07-09 16:15 UTC by marmuc680

Added package formats supported in partner center.

.MSIXVC and .XVC (including GameCore)

2020-07-09 16:15 UTC, PRMerger9 commented
@marmuc680 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-07-10 18:50 UTC, hickeys requested changes

2020-07-10 18:50 UTC, hickeys commented on windows-apps-src/publish/upload-app-packages.md
> +The **Packages** page is where you upload all of the package files (.msix, .msixupload, .msixbundle, .appx, .appxupload, and/or .appxbundle .MSIXVC .XVC (including GameCore)) for the app that you're
Please move the "and/or" that is currently after ".appxupload" and put it after ".MSIXVC"

Please also add commas between each file extension in the list. 

Then it looks good to go!

2020-07-27 15:41 UTC, ktoliver commented
Hi @marmuc680 - As discussed in email, this update should be made in the private repo. We'll close this PR. Thanks very much.

2020-07-27 15:44 UTC, ktoliver commented
To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the repo name in the URL. 

![image](https://user-images.githubusercontent.com/19416435/88313501-7cf24880-ccc8-11ea-9f03-4e4d4a2f8288.png)

Also, [SpineEdit](https://review.docs.microsoft.com/help/contribute/contribute-tool-spineedit?branch=master) is a Chrome extension that opens the edit option in the private repo, if there is one and if you have access to it.

<hr>

Related links in the [internal Microsoft Docs contributor guide](https://review.docs.microsoft.com/help/contribute/?branch=master):

[**Public vs. private repos**](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) | [**Move a commit to a different repo (public -> private)**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication) | [**GitHub for content reviews**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-reviews?branch=master)
[**Quick reference for contributing to the docs**](https://review.docs.microsoft.com/help/contribute/contribute-quick-reference?branch=master) | [**Make changes to a Docs article**](https://review.docs.microsoft.com/help/contribute/edit-doc-with-vs-code-and-git-cli?branch=master) | [**PR review quality criteria**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master)

2020-07-27 15:53 UTC, ktoliver commented
Per Teams convo, we'll reopen this PR.

2020-08-14 18:41 UTC, ktoliver commented
Conversation moved to email

2020-09-21 20:27 UTC, closed without merging