VPN interface
MicrosoftDocs/windows-uwp pull request #3350
Opened 2021-09-15 09:25 UTC by demonethic-office

2021-09-15 09:25 UTC, PRMerger18 commented
@demonethic-office : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-15 16:02 UTC, ktoliver commented
#label:"aq-pr-triaged"

2021-09-30 18:36 UTC, hickeys requested changes
Just one quick change and this is good to go

2021-09-30 18:36 UTC, hickeys commented on hub/apps/design/shell/tiles-and-notifications/firewall-allowlist-config.md
> +> [!Note]V
Please remove the V at the end of this line.

2021-10-01 10:23 UTC, PRMerger16 commented
@demonethic-office : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-10-01 16:09 UTC, hickeys approved these changes

2021-10-01 16:09 UTC, merged