minor changes to wording
MicrosoftDocs/windows-uwp pull request #3840
Opened 2022-05-17 01:48 UTC by arianapadilla

2022-05-17 01:48 UTC, PRMerger15 commented
@arianapadilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-17 16:06 UTC, Jak-MS commented
@arianapadilla - can you resolve the merge conflicts?  After that, @Karl-Bridge-Microsoft can review the changes.

2022-05-18 18:56 UTC, Jay-o-Way requested changes

2022-05-18 18:56 UTC, Jay-o-Way commented on hub/apps/design/globalizing/use-mat.md
> +The Multilingual App Toolkit Visual Studio (MAT VS) extension collects anonymous usage data and sends it to Microsoft servers to help improve our products and services. Telemetry is off by default an
```suggestion
The Multilingual App Toolkit Visual Studio (MAT VS) extension collects anonymous usage data and sends it to Microsoft servers to help improve our products and services. Telemetry is off by default and can be enabled or disabled at any time. For more details, see [Multilingual App Toolkit 4.0 FAQ & troubleshooting](windows/apps/design/globalizing/mat-faq-troubleshooting).
```
Don't hardcode these the beginning or _lang_ codes.

2022-05-23 16:42 UTC, PRMerger10 commented
@arianapadilla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-23 16:50 UTC, Karl-Bridge-Microsoft approved these changes

2022-05-23 16:50 UTC, PRMerger12 commented
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-23 16:52 UTC, PRMerger12 commented
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-23 16:52 UTC, Karl-Bridge-Microsoft approved these changes

2022-05-23 16:52 UTC, merged