Adding in color name setting
MicrosoftDocs/windows-uwp pull request #3855
Opened 2022-05-27 05:01 UTC by crutkas

This setting wasn't included in the doc

2022-05-27 05:01 UTC, PRMerger19 commented
@crutkas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-27 16:03 UTC, Court72 commented
@mattwojo 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

2022-05-30 17:28 UTC, htcfreek requested changes

2022-05-30 17:28 UTC, htcfreek commented on hub/powertoys/color-picker.md
> +   - The shown color name will be a high-level representation of the color. Example: Light Green, Green, Dark Green.
has to be switched with the copy format (see order on screenshot)

2022-06-05 17:56 UTC, Jay-o-Way commented on hub/powertoys/color-picker.md
>  - Format of a copied color (HEX, RGB, etc.)
```suggestion
- Format of a copied color (HEX, RGB, etc.)
- Show the name of the color. The shown color name will be a high-level representation of the color. Example: Light Green, Green, Dark Green.
```

2022-06-05 18:49 UTC, PRMerger17 commented
@crutkas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-13 20:58 UTC, mattwojo approved these changes

2022-06-13 20:58 UTC, mattwojo commented
#sign-off

2022-06-13 21:41 UTC, htcfreek approved these changes
LGTM

2022-06-13 21:59 UTC, merged