Fix a few typos
MicrosoftDocs/windows-uwp pull request #4950
Opened 2024-04-13 12:30 UTC by Blake-Madden

Misspellings, article mismatches

2024-04-23 00:02 UTC, Jay-o-Way commented
LGTM

2024-05-30 12:33 UTC, Jay-o-Way requested changes
Great job! just _one_ little thing :)

2024-05-30 12:33 UTC, Jay-o-Way commented on hub/apps/design/controls/contact-card.md
> +* As a standard contact card that appears in a flyout that is light-dismissable--the contact card disapears when the user clicks outside of it.
double P please

2024-05-31 01:36 UTC, Blake-Madden commented on hub/apps/design/controls/contact-card.md
> +* As a standard contact card that appears in a flyout that is light-dismissable--the contact card disapears when the user clicks outside of it.
Got it.

2024-06-13 18:13 UTC, GrantMeStrength commented
Wow thanks for fixing all these!

2024-06-13 20:36 UTC, merged