Update peek.md
MicrosoftDocs/windows-uwp pull request #5168
Opened 2024-10-13 21:02 UTC by daverayment

Added information about new Delete function.

Added references to Peek being able to preview videos and folder summaries, in addition to being able to hover over previews for tooltip information.

2024-10-13 21:15 UTC, daverayment commented
The Delete function's PR is https://github.com/microsoft/PowerToys/pull/35418.

2024-10-14 13:38 UTC, alvinashcraft reviewed
Just a minor suggestion to turn the note into a Tip box. Which PT release will contain these updates?

2024-10-14 13:38 UTC, alvinashcraft commented on hub/powertoys/peek.md
> +Note: only files may be deleted. Folders may not be deleted, even if they are empty.
```suggestion
> [!TIP]
> Only files may be deleted. Folders may not be deleted, even if they are empty.
```

2024-10-14 16:52 UTC, daverayment commented
@alvinashcraft Thank you very much for the suggestion, which I've accepted and committed.

I'm afraid I've only just submitted the PR for the Delete functionality itself, so it hasn't been through code review or planned for inclusion in a release yet. This is the first time I've updated the docs along with a feature, so I don't know how the code and docs repos are aligned - should I comment again here once I know which version will include the code?

2024-10-14 17:00 UTC, alvinashcraft commented
Hi @daverayment. No worries. I have a few other PowerToys PRs that I've been holding onto while waiting for a release to go out. If you happen to hear when this gets assigned to a release, a comment here would be appreciated. Otherwise, I'll keep an eye on the status of your PR as each release goes out.

2024-10-26 17:43 UTC, Jay-o-Way commented
@daverayment thank for this pr. Please do link the related (PowerToys) PRs too, if you will? :)

2024-10-26 18:33 UTC, daverayment commented
@Jay-o-Way There is a mention to the dev PR earlier in the thread on October 13th. Sorry, I should have also included a link in the initial comment.

It's https://github.com/microsoft/PowerToys/pull/35418

2025-01-26 22:31 UTC, daverayment commented
@alvinashcraft @Jay-o-Way This updated PR includes additional documentation for the Peek Delete functionality. This was originally delayed from a prior PowerToys release to incorporate a few more requests from the code review, including a new confirmation dialog and a settings option.

I'm unsure whether the feature will land in 0.88, but I will ask on the main code PR and let you know.

2025-01-27 14:08 UTC, alvinashcraft requested changes
A few suggestions inline. Mostly minor things. Thanks for the update!

2025-01-27 14:08 UTC, alvinashcraft commented on hub/powertoys/peek.md
> +ms.date: 08/03/2023
The ms.date should be updated to something more current.

2025-01-27 14:08 UTC, alvinashcraft commented on hub/powertoys/peek.md
> -ms.topic: concept-article
Please keep this new ms.topic type. It's one of our content patterns supported by some new tooling.

2025-01-27 14:08 UTC, alvinashcraft commented on hub/powertoys/peek.md
> -# Customer intent: Learn how to configure and use the Peek utility in PowerToys.
Please keep the "Customer intent". We're adding this for all content that uses one of the supported content pattern types.

2025-01-27 14:08 UTC, alvinashcraft commented on hub/powertoys/peek.md
> +The Peek window adjusts its size based on the dimensions of the images being previewed. However, if you prefer to keep the window's size and position, you can use the pinning feature.
Minor. If this is to be separate paragraphs, there must be an extra space between them or they'll be combined without any line feed.
```suggestion
The Peek window adjusts its size based on the dimensions of the images being previewed. However, if you prefer to keep the window's size and position, you can use the pinning feature.

```

2025-01-27 14:08 UTC, alvinashcraft commented on hub/powertoys/peek.md
> +![Example of Peek's file deletion confirmation dialog](../images/pt-peek-delete-confirmation.png)
Minor suggestion. I try to begin alt text with "A screenshot of" or "A picture of", etc:
```suggestion
![A screenshot of Peek's file deletion confirmation dialog](../images/pt-peek-delete-confirmation.png)
```

2025-01-28 01:19 UTC, daverayment commented on hub/powertoys/peek.md
> +ms.date: 08/03/2023
Ah. Sorry about this, the ms.topic and Customer Intent changes. This was because I edited the page as it was back in October when the original PR was raised. I will restore them in a new commit.

2025-01-28 14:39 UTC, alvinashcraft approved these changes
Thanks, Dave! This looks good. I'll hang onto it until the update goes out in a release.

2025-01-28 19:31 UTC, daverayment commented
Thank you, @alvinashcraft. I've made a small update to reflect a simplification to the new confirmation dialog. Hopefully that's the last of the changes 🤞

2025-02-03 13:57 UTC, alvinashcraft approved these changes
Updates look good. Thanks, @daverayment! Let me know if you hear about when this gets into a release.

2025-03-31 23:12 UTC, merged